CREATE TABLE DEPARTMENT (
	ID IDENTITY NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID),
	CONSTRAINT DEPARTMENT_UNIQUE_NAME UNIQUE (NAME)
);

INSERT INTO DEPARTMENT (NAME)
	VALUES ('Engineering');
INSERT INTO DEPARTMENT (NAME)
	VALUES ('Product');
