CREATE TABLE EMPLOYEE_POSITION (
	ID IDENTITY NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	PROMOTION_WEIGHT SMALLINT NOT NULL,
	CONSTRAINT POSITION_PK PRIMARY KEY (ID),
	CONSTRAINT POSITION_UNIQUE_NAME UNIQUE (NAME)
);

INSERT INTO EMPLOYEE_POSITION (NAME,PROMOTION_WEIGHT)
	VALUES ('Software Engineer',1);
INSERT INTO EMPLOYEE_POSITION (NAME,PROMOTION_WEIGHT)
	VALUES ('QA Engineer',2);
INSERT INTO EMPLOYEE_POSITION (NAME,PROMOTION_WEIGHT)
	VALUES ('DevOps Engineer',1);
INSERT INTO EMPLOYEE_POSITION (NAME,PROMOTION_WEIGHT)
	VALUES ('Project Manager',3);
INSERT INTO EMPLOYEE_POSITION (NAME,PROMOTION_WEIGHT)
	VALUES ('Human Resources',2);
