CREATE TABLE EMPLOYEE_STATUS (
	ID IDENTITY NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	PROMOTION_WEIGHT SMALLINT NOT NULL,
	CONSTRAINT STATUS_PK PRIMARY KEY (ID),
	CONSTRAINT STATUS_UNIQUE_NAME UNIQUE (NAME)
);

INSERT INTO EMPLOYEE_STATUS (NAME,PROMOTION_WEIGHT)
	VALUES ('In Probation',3);
INSERT INTO EMPLOYEE_STATUS (NAME,PROMOTION_WEIGHT)
	VALUES ('Active',2);
INSERT INTO EMPLOYEE_STATUS (NAME,PROMOTION_WEIGHT)
	VALUES ('Maternity Leave',2);
INSERT INTO EMPLOYEE_STATUS (NAME,PROMOTION_WEIGHT)
	VALUES ('Paternal Leave',2);
INSERT INTO EMPLOYEE_STATUS (NAME,PROMOTION_WEIGHT)
	VALUES ('Vacation',2);
INSERT INTO EMPLOYEE_STATUS (NAME,PROMOTION_WEIGHT)
	VALUES ('In Resignation',1);
