CREATE TABLE EMPLOYEE_SENIORITY (
	ID IDENTITY NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	PROMOTION_WEIGHT SMALLINT NOT NULL,
	CONSTRAINT SENIORITY_PK PRIMARY KEY (ID),
	CONSTRAINT SENIORITY_UNIQUE_NAME UNIQUE (NAME)
);

INSERT INTO EMPLOYEE_SENIORITY (NAME,PROMOTION_WEIGHT)
	VALUES ('Senior',3);
INSERT INTO EMPLOYEE_SENIORITY (NAME,PROMOTION_WEIGHT)
	VALUES ('Mid',2);
INSERT INTO EMPLOYEE_SENIORITY (NAME,PROMOTION_WEIGHT)
	VALUES ('Junior',1);
