CREATE TABLE EMPLOYEE (
	ID IDENTITY NOT NULL,
	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(128) NOT NULL,
	DEPARTMENT_ID BIGINT,
	POSITION_ID BIGINT NOT NULL,
	SENIORITY_ID BIGINT NOT NULL,
	STATUS_ID BIGINT NOT NULL,
	CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID),
	CONSTRAINT EMPLOYEES_DEPARTMENT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES PUBLIC.DEPARTMENT(ID),
	CONSTRAINT EMPLOYEES_POSITION_FK FOREIGN KEY (POSITION_ID) REFERENCES PUBLIC.EMPLOYEE_POSITION(ID),
	CONSTRAINT EMPLOYEES_SENIORITY_FK FOREIGN KEY (SENIORITY_ID) REFERENCES PUBLIC.EMPLOYEE_SENIORITY(ID),
	CONSTRAINT EMPLOYEES_STATUS_FK FOREIGN KEY (STATUS_ID) REFERENCES PUBLIC.EMPLOYEE_STATUS(ID)
);

INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,DEPARTMENT_ID,POSITION_ID,SENIORITY_ID,EMAIL,STATUS_ID)
	VALUES ('Andrey','Strinski',1,1,1,'andrey.strinski@email.com',2);
